### ISSUE TITLE
Add support for POSTing to "North Star" DS User API

### ISSUE THREAD

**Issue by DeeZone** [DoSomething/mbc-userAPI-registration#10]
The DoSomething.org User API "North Star" will have all user registrations details submitted via a cURL.

**North Star** `/users` POST docs: https://github.com/DoSomething/northstar/wiki/Spec#registering-a-user

**Comment by DeeZone** [comment]
@jonuy Can you please point me to or supply the end point details for the "North Star" end point that new user submissions should be made to.

**Comment by jonuy** [comment]
https://github.com/DoSomething/northstar/wiki/Spec#registering-a-user

**Comment by DeeZone** [comment]
Request submitted to @angaither for a `APPLICATION_ID` and `REST_API_KEY`.

**Comment by DeeZone** [comment]
@jonuy Can you walk me through the API key generation process? It appears I need a `APPLICATION_ID` and `REST_API_KEY` to make a `/users` call to create a user

First:
```
curl -X POST \
  -H "X-DS-Application-Id: ${APPLICATION_ID}" \
  -H "X-DS-REST-API-Key: ${REST_API_KEY}" \
  -d {login data} \
  http://api.dosomething.org/1/login
```
then:
```
curl -X POST \
  -H "X-DS-Application-Id: ${APPLICATION_ID}" \
  -H "X-DS-REST-API-Key: ${REST_API_KEY}" \
  -d {create data} \
  http://api.dosomething.org/1/users
```

**Comment by DeeZone** [comment]
What values should be POSTed to Northstar when creating users? The documentation example suggests only:
- email: String,
- mobile: String,
- password: String,
- birthdate: Date,
- first_name: String
Currently `mb-users` has user documents with the following fields:
```
> db['mailchimp-users'].find({email: "xxx@gmail.com"}).pretty()
{
	"_id" : ObjectId("540be248a593a11d23d073f4"),
	"address1" : "111 starsia st",
	"birthdate" : ISODate("1000-00-00T05:00:00Z"),
	"campaigns" : [
		{
			"nid" : 2461,
			"signup" : ISODate("2014-09-07T04:42:50Z"),
			"_id" : ObjectId("540be249216e3b24533e51b6")
		}
	],
	"city" : "Westminster",
	"college_name" : "Chapman University",
	"degree_type" : "Master",
	"drupal_register_date" : ISODate("2015-03-31T21:42:35Z"),
	"drupal_uid" : 1234,
	"email" : "xxxx@gmail.com",
	"first_name" : "yvonne",
	"gpa" : 1.xx,
	"hs_gradyear" : 2015,
	"hs_name" : "Bolsa Grande High School",
	"last_name" : "pham",
	"major_name" : "Economics",
	"mobile" : "1234567890",
	"race" : "A",
	"religion" : "Buddhist",
	"role" : "HSstudent",
	"sat_math" : 000,
	"sat_verbal" : 000,
	"sat_writing" : 000,
	"source" : "niche",
	"state" : "CA",
	"subscribed" : 1,
	"zip" : "99999"
}
```
are any of these of value to Northstar? Should they all be POSTed when available?

**Comment by DeeZone** [comment]
@jonuy Talked to @angaither , I have the `${APPLICATION_ID}"` and `${REST_API_KEY}` values. Still looking for input on what values should be posted. Perhaps just stick to the suggestions in the docs?

**Comment by angaither** [comment]
@DeeZone woah, how did you get all that info??
Maybe we should build in some more fields?? @jonuy 

current the app supports the following fields
email
mobile
password
address_street1
address_street2
address_city
address_state
address_zip
country
birthdate
first_name 
last_name

as well as the ID from the source
drupal_id
cgg_id

**Comment by jonuy** [comment]
@angaither Yea, if the message broker stuff is getting this data, we should allow Northstar to accept it too. I added an issue here (https://github.com/DoSomething/northstar/issues/63)

@DeeZone Feel free to POST all the user data towards Northstar anyway. It'll just filter for expected fields for now and will take the rest when we update it to.

You'll also want to make note to change the `drupal_uid` to `drupal_id` when POSTing data. ... hm, and whatever other spellings or field namings may be different.
